Use new/delete instead of malloc()/free() to make newer GCC and Clang happy
Resolves:
error: use of deleted function ‘private_t& private_t::operator=(private_t&&)’

and:
error: object of type 'private_t' cannot be assigned because its copy assignment operator is implicitly deleted