Revert "Use atomics for protected-ints on other *nixes too (not just FreeBSD)"
This reverts commit e1e034cc4d969c30573d26d87c8d65d53458590b.

Didn't work for .cpp files:
stdatomic.h:40:9: error: ‘_Atomic’ does not name a type
typedef _Atomic _Bool atomic_bool