Use int64_t instead of la_int64_t
Resolve error reported on irc with Ubuntu (don't know what version):
<rjwboys> ok now i get filedat.c:896:3: error: unknown type name ‘la_int64_t’