Fix typo that cause some (not all?) *nix compiles to fail
error: passing argument 1 of 'newuserdefaults' from incompatible pointer type

Weird they didn't all fail.