Fix 2 errors: TypeError: ee.protocol[0] is undefined: sometimes there just ain't no protocol? graphic.js line 113: TypeError: bin is null: the BBS previews are LZ-compressed and thus must be passed through lib.decode_preview() to get the raw data.