Catch and log exceptions if FileBase.get_path() fails
I saw this in my error.log:

evnt DELFILES !JavaScript  /sbbs/exec/delfiles.js line 100:
     Error: -110 loading file 'somefile.name'

Which would terminate the script. We don't need to do that, just log it
and continue on.

Other changes of no consequence.