The latest cryptlib 3.4.5 patched by Deuce
How I accomplished this (since I tend for forget):

1. Copy the 3rdp/src/cl from a current *nix build to a system w/MSVC2022
2. Remove the I/O/eap*.c files from the project (don't exist, not needed)
3. Change the build configuration to Win32 Release
4. Resolve misc\int_api.c(700,16): error C2099: initializer is not a constant

   misc\int_api.c int_api.c
   697a698,700
   > #undef CURRENT_TIME_VALUE
   > #define CURRENT_TIME_VALUE 0x6588BADC

I guess this version of MSVC isn't "tough enough",  though apparently MSVC2017
was.

This should fix CI builds.