Hack around the protected_uint32_t allocation issue
macOS builds failling with link errors:

Undefined symbols for architecture arm64:
  "operator new(unsigned long)", referenced from:
      _services_thread in services.o
ld: symbol(s) not found for architecture arm64

and

Undefined symbols for architecture x86_64:
  "operator new(unsigned long)", referenced from:
      _services_thread in services.o
ld: symbol(s) not found for architecture x86_64

We need to use new for when the std Atomic class is used however, since we
need (?) to invoke the constructor.