Restore the 'environ' declaration removed in previous commit (C++ migration)
Needed for FreeBSD build apparently:
jsexec.cpp:1561:16: error: use of undeclared identifier 'environ'

Even though we get a (new) warning when built w/MSVC:
warning C4273: '__p__environ': inconsistent dll linkage