Use the sub-board internal as the default 'listname' if there is 'from' key specified in the sub-board sections of the listgate.ini
This resolves the reported run-time error (due to misconfiguration):
10/13 09:59:23p !JavaScript d:\sbbs\mods\listgate.js line 86:
TypeError: from is undefined