Fix bbs.compare_ars() called with no params
Throws an exception now instead of using uninitialized args:

;eval
Parameter(s): bbs.compare_ars()
InternalError: allocation size overflow

Updated JSDOCS for methods (mostly just adding punctuation). Fixed a typo
or two.